---
# Documentation is built using Github Actions.
# CircleCI is only used to download the artifacts in order to host
# and deploy them.

version: 2.1

# Parameters required to trigger the execution
# of the "host_docs" job
parameters:
    GITHUB_RUN_URL:
        type: string
        default: none
    STATUS:
        type: string
        default: failure

jobs:
    host_docs:
        machine:
            image: ubuntu-2004:current
        environment:
            GITHUB_ARTIFACT_URL: << pipeline.parameters.GITHUB_RUN_URL >>/doc.zip
        steps:
        -   checkout
        -   run: bash build_tools/circle/download_documentation.sh
        -   store_artifacts:
                path: doc/_build/html/
                destination: dev
      # Persists the generated documentation, so that it
      # can be attached and deployed in the "deploy" job
        -   persist_to_workspace:
                root: doc/_build
                paths:
                -   html

    deploy:
        docker:
        -   image: circleci/python:3.9
        environment:
            STATUS: << pipeline.parameters.STATUS >>
        steps:
        -   run:
                name: Deploy dev docs
                command: |
                    echo $STATUS
                    if [[ "$STATUS" == "success" ]]; then
                        echo "Mocking deployment..."
                    else
                        echo "Failed to deploy because doc build status is "failure"
                        exit 1
                    fi

workflows:
    version: 2

    host_and_deploy_doc:
        when:
            not:
                equal: [none, << pipeline.parameters.GITHUB_RUN_URL >>]

    # The jobs should run only when triggered by the workflow
        jobs:
        -   host_docs
        -   deploy:
                requires:
                -   host_docs
                filters:
                    branches:
                        only:
                        -   main
