# Workflow to trigger the jobs that will host the documentation
name: Documentation push trigger
on:
  workflow_run:
    # Run the workflow after the separate "Documentation builder" workflow completes
    workflows: [Documentation builder]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    # Run the job only if the "Documentation builder" workflow succeeded
    # Prevents this workflow from running on a fork.
    # To test this workflow on a fork remove the `github.repository == ymzayek/nilearn` condition
    if: github.repository == 'ymzayek/nilearn' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout nilearn
        uses: actions/checkout@v3

      - name: Trigger hosting jobs
        run: bash build_tools/github/trigger_hosting.sh
        env:
          CIRCLE_CI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          COMMIT_SHA:  ${{ github.event.pull_request.head.sha }}
          REPO_NAME:  ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
